// flow-typed signature: 01828e221f426b182afe8d50abd0384a
// flow-typed version: <<STUB>>/expo_v*/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare module.exports: any;
}
