// flow-typed signature: f76e1f0b97b0e594373a75a91797e923
// flow-typed version: <<STUB>>/react-native_v*/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native' {
  declare module.exports: any;
}
